language: go

go:
  - 1.7

services:
  - rabbitmq

env:
  - AMQP_URI=amqp://guest:guest@127.0.0.1:5672// GOMAXPROCS=4

before_install:
  - go get github.com/satori/go.uuid
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/streadway/amqp

script:
  - go test -v -covermode=count -coverprofile=cover.out ./...

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out
